#! /bin/bash

#bash reads:[command][arguments]

#if there are no arguments
whtout(){
	if [[ $# -eq 0 ]];then
		echo "A quick script to shred files before deletion using built-ins /n"
		echo "Usage: ./whtout [filename]"
		
#when there is an argument
	else
		cat /dev/null > "$1"
		rm "$1"
			
	fi
}